## 1 相机启动

In [9]:
import pyzed.sl as sl
import cv2

In [10]:
# Create a ZED camera object
zed = sl.Camera()

# Set configuration parameters
init_params = sl.InitParameters()
init_params.sdk_verbose = 0
init_params.camera_resolution = sl.RESOLUTION.HD1080
init_params.camera_fps = 30
init_params.camera_disable_self_calib = True
init_params.depth_mode = sl.DEPTH_MODE.NEURAL_PLUS

In [11]:
# Open the camera
err = zed.open(init_params)
if err != sl.ERROR_CODE.SUCCESS:
    print("Camera Open : "+repr(err)+". Exit program.")
    exit(-1)
zed_info = zed.get_camera_information()
# zed_info.camera_configuration.calibration_parameters.left_cam.fx = 1050.0
print('相机序列号：%s' % zed_info.serial_number)
print('相机型号：%s' % zed_info.camera_model)
print('相机分辨率: width:%s, height:%s' % (zed_info.camera_configuration.resolution.width, zed_info.camera_configuration.resolution.height))
print('相机FPS：%s' % zed_info.camera_configuration.fps)
print('相机内部参数：')
print('左相机焦距fx：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.fx)
print('左相机焦距fy：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.fy)
print('左相机光心cx：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.cx)
print('左相机光心cy：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.cy)
print('左相机畸变系数：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.disto)
print('右相机焦距fx：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.fx)
print('右相机焦距fy：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.fy)
print('右相机光心cx：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.cx)
print('右相机光心cy：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.cy)
print('右相机畸变系数：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.disto)
print('相机齐次变换矩阵：\n%s' % zed_info.camera_configuration.calibration_parameters.stereo_transform.m)
print('相机基距：%s' % zed_info.camera_configuration.calibration_parameters.get_camera_baseline())
print('初始化参数：')
zed_init = zed.get_init_parameters()
print('相机分辨率：%s' % (zed_init.camera_resolution))
print('深度最小：%s' % (zed_init.depth_minimum_distance))
print('深度最大：%s' % (zed_init.depth_maximum_distance))
# 关闭相机
zed.close()

相机序列号：34680631
相机型号：ZED 2i
相机分辨率: width:1920, height:1080
相机FPS：30.0
相机内部参数：
左相机焦距fx：1070.642578125
左相机焦距fy：1070.642578125
左相机光心cx：982.0308837890625
左相机光心cy：552.5791625976562
左相机畸变系数：[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
右相机焦距fx：1070.642578125
右相机焦距fy：1070.642578125
右相机光心cx：982.0308837890625
右相机光心cy：552.5791625976562
右相机畸变系数：[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
相机齐次变换矩阵：
[[  1.           0.           0.         120.17098999]
 [  0.           1.           0.           0.        ]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]]
相机基距：120.17098999023438
初始化参数：
相机分辨率：RESOLUTION.HD1080
深度最小：200.30392456054688
深度最大：20000.0


In [ ]:
# 关闭相机
zed.close()

In [ ]:
# Open the camera
err = zed.open(init_params)
if err != sl.ERROR_CODE.SUCCESS:
    print("Camera Open : "+repr(err)+". Exit program.")
    exit(-1)
zed_info = zed.get_camera_information()
print('相机序列号：%s' % zed_info.serial_number)
print('相机型号：%s' % zed_info.camera_model)
print('相机分辨率: width:%s, height:%s' % (zed_info.camera_configuration.resolution.width, zed_info.camera_configuration.resolution.height))
print('相机FPS：%s' % zed_info.camera_configuration.fps)
print('相机内部参数：')
print('左相机焦距fx：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.fx)
print('左相机焦距fy：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.fy)
print('左相机光心cx：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.cx)
print('左相机光心cy：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.cy)
print('左相机畸变系数：%s' % zed_info.camera_configuration.calibration_parameters.left_cam.disto)
print('右相机焦距fx：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.fx)
print('右相机焦距fy：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.fy)
print('右相机光心cx：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.cx)
print('右相机光心cy：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.cy)
print('右相机畸变系数：%s' % zed_info.camera_configuration.calibration_parameters.right_cam.disto)
print('相机齐次变换矩阵：\n%s' % zed_info.camera_configuration.calibration_parameters.stereo_transform.m)
print('相机基距：%s' % zed_info.camera_configuration.calibration_parameters.get_camera_baseline())
print('初始化参数：')
zed_init = zed.get_init_parameters()
print('相机分辨率：%s' % (zed_init.camera_resolution))
print('深度最小：%s' % (zed_init.depth_minimum_distance))
print('深度最大：%s' % (zed_init.depth_maximum_distance))
# 关闭相机
zed.close()

相机序列号：34680631
相机型号：ZED 2i
相机分辨率: width:1920, height:1080
相机FPS：30.0
相机外部参数：
左相机焦距fx：1070.340087890625
左相机焦距fy：1070.340087890625
左相机光心cx：982.0335693359375
左相机光心cy：552.5728759765625
左相机畸变系数：[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
右相机焦距fx：1070.340087890625
右相机焦距fy：1070.340087890625
右相机光心cx：982.0335693359375
右相机光心cy：552.5728759765625
右相机畸变系数：[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
相机齐次变换矩阵：
[[  1.           0.           0.         120.17098999]
 [  0.           1.           0.           0.        ]
 [  0.           0.           1.           0.        ]
 [  0.           0.           0.           1.        ]]
相机基距：120.17098999023438
初始化参数：
相机分辨率：RESOLUTION.HD1080
深度最小：199.3722686767578
深度最大：20000.0


In [4]:
image = sl.Mat()
depth_map = sl.Mat()
runtime_parameters = sl.RuntimeParameters()
# Open the camera
err = zed.open(init_params)
if err != sl.ERROR_CODE.SUCCESS:
    print("Camera Open : "+repr(err)+". Exit program.")
    exit(-1)
if zed.grab(runtime_parameters) == sl.ERROR_CODE.SUCCESS :
    print('grab success')
    # A new image and depth is available if grab() returns SUCCESS
    zed.retrieve_image(image, sl.VIEW.LEFT) # Retrieve left image
    zed.retrieve_measure(depth_map, sl.MEASURE.DEPTH) # Retrieve depth

grab success


In [30]:
# 关闭相机
zed.close()

In [5]:
depth_map.get_data()

array([[      nan,       nan,       nan, ..., 648.20483, 648.04645,
        648.05634],
       [      nan,       nan,       nan, ..., 648.0793 , 648.05164,
        648.1935 ],
       [      nan,       nan,       nan, ..., 648.0922 , 648.1681 ,
        648.3462 ],
       ...,
       [      nan,       nan,       nan, ..., 772.0501 , 772.05237,
        772.0618 ],
       [      nan,       nan,       nan, ..., 772.077  , 772.08386,
        772.09515],
       [      nan,       nan,       nan, ..., 772.1105 , 772.11945,
        772.12683]], dtype=float32)

In [9]:
x, y = 256, 256  # 中心点
depth_value = depth_map.get_value(x, y)
depth_value

(SUCCESS, nan)

## 2 目标检测

In [1]:
import pyzed.sl as sl
import cv2
import numpy as np

In [2]:
# Create a ZED camera object
zed = sl.Camera()

# Set configuration parameters
init_params = sl.InitParameters()
init_params.sdk_verbose = 0
init_params.camera_resolution = sl.RESOLUTION.HD720
init_params.camera_fps = 30

# Open the camera
err = zed.open(init_params)
if err != sl.ERROR_CODE.SUCCESS:
    print("Camera Open : "+repr(err)+". Exit program.")
    exit(-1)

# Get camera information (ZED serial number)
zed_serial = zed.get_camera_information().serial_number
print("Hello! This is my serial number: {0}".format(zed_serial))

# Close the camera
# zed.close()

Hello! This is my serial number: 34680631


In [3]:
# Define the Object Detection module parameters
detection_parameters = sl.ObjectDetectionParameters()
detection_parameters.enable_tracking = True
detection_parameters.enable_segmentation = True

# Object tracking requires camera tracking to be enabled
if detection_parameters.enable_tracking:
    zed.enable_positional_tracking()


In [4]:
print("Object Detection: Loading Module...")
err = zed.enable_object_detection(detection_parameters)
if err != sl.ERROR_CODE.SUCCESS:
    print("Error {}, exit program".format(err))
    zed.close()
    exit()

Object Detection: Loading Module...


In [9]:
# Set runtime parameter confidence to 40
detection_parameters_runtime = sl.ObjectDetectionRuntimeParameters()
detection_parameters_runtime.detection_confidence_threshold = 40

objects = sl.Objects()
image_zed = sl.Mat()
type = 'mask'

# Grab new frames and detect objects
while zed.grab() == sl.ERROR_CODE.SUCCESS:
    err = zed.retrieve_objects(objects, detection_parameters_runtime)
    zed.retrieve_image(image_zed, sl.VIEW.LEFT)
    image_ocv = image_zed.get_data()[:, :, :3].copy()

    if type == 'box_2d':
        for obj in objects.object_list:
            print(obj.bounding_box_2d.astype(np.int32))
            vertices = obj.bounding_box_2d.astype(np.int32)
            cv2.polylines(image_ocv, [vertices], isClosed=True, color=(0, 255, 0), thickness=2)
        cv2.imshow("Image", image_ocv)
    elif type == 'mask':
        highlighted_image = image_ocv.copy()
        for obj in objects.object_list:
            binary_mask = obj.mask.get_data()
            vertices = obj.bounding_box_2d.astype(np.int32)
            # 计算边界框的最小x, 最大x, 最小y, 最大y
            x_min = min([v[0] for v in vertices])
            x_max = max([v[0] for v in vertices])
            y_min = min([v[1] for v in vertices])
            y_max = max([v[1] for v in vertices])
            # 创建一个全图尺寸的空掩模
            full_size_mask = np.zeros(image_ocv.shape[:2], dtype=np.uint8)
            # 将局部掩码放置到全图掩模的正确位置
            full_size_mask[y_min:y_max, x_min:x_max] = binary_mask
            colored_mask = cv2.cvtColor(full_size_mask, cv2.COLOR_GRAY2BGR)
            colored_mask[full_size_mask > 0] = [0, 0, 255]
            print(highlighted_image.shape)
            print(colored_mask.shape)
            highlighted_image = cv2.addWeighted(highlighted_image, 1, colored_mask, 0.5, 0)
        cv2.imshow('Image with Mask', highlighted_image)

    
    if cv2.waitKey(1) == ord('c'):
        cv2.destroyAllWindows()
        break


    # if objects.is_new:
    #     # Count the number of objects detected
    #     print("{} Object(s) detected".format(len(objects.object_list)))

    #     if len(objects.object_list):
    #         # Display the 3D location of an object
    #         first_object = objects.object_list[0]
    #         position = first_object.position
    #         print(" 3D position : [{0},{1},{2}]".format(position[0],position[1],position[2]))

    #         # Display its 3D bounding box coordinates
    #         bounding_box = first_object.bounding_box
    #         print(" Bounding box 3D :")
    #         for it in bounding_box:            
    #             print(" " + str(it), end='')


(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280, 3)
(720, 1280