# 1 SDK测试

In [1]:
from utils.HansRobot.CPS import CPSClient

In [3]:
tcp_host_ip = '192.168.4.40'
tcp_port = 10003
cps = CPSClient()
cps.HRIF_Connect(0, tcp_host_ip, tcp_port)

http://192.168.4.40:20000


0

In [137]:
cps.HRIF_DisConnect(0)

0

In [46]:
cps.HRIF_GrpEnable(0, 0)

0

In [151]:
cps.HRIF_GrpDisable(0,0)

0

In [141]:
cps.HRIF_GrpReset(0,0)

39500

In [65]:
dOverride = 0.1
cps.HRIF_SetOverride(0,0, dOverride)

0

In [161]:
cps.HRIF_MoveRelL(0, 0, 3, 1, 10, 1)
# 判断是否运动完成，运动完成后才能下发一个指令
while True:
    result = []
    cps.HRIF_IsMotionDone(0, 0, result)
    if result[0]:
        break

MoveRelL,0,3,1,10,1,;


In [25]:
cps.HRIF_GrpReset(0,0)

0

In [58]:
cps.HRIF_GrpStop(0, 0)

0

In [68]:
import numpy as np
from scipy.spatial.transform import Rotation as R

0

In [50]:
cps.HRIF_GrpOpenFreeDriver(0,0)

0

In [46]:
# 定义返回值空列表
result = []
# 读取当前实际位置信息
cps.HRIF_ReadActPos(0,0, result)
result

['1.666',
 '13.922',
 '97.327',
 '2.368',
 '92.273',
 '-6.453',
 '337.131',
 '16.207',
 '482.644',
 '178.142',
 '4.562',
 '-171.772',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000',
 '0.000']

In [47]:
# 定义返回值空列表
result = [ ]
# 读取 TCP 实际位置
nRet = cps.HRIF_ReadActTcpPos(0,0,result)
# 读取 TCP 实际位置变量
result

['1.666', '13.922', '97.327', '2.368', '92.273', '-6.453']

In [179]:
# 定义返回值空列表
result = [ ]
# 读取最大直线速度
cps.HRIF_ReadLinearMaxSpeed(0, 0, result)
result

['2000.000', '2500.000', '10000000.000']

In [180]:
# 定义返回值空列表
result = [ ]
# 读取最大关节速度
cps.HRIF_ReadJointMaxVel(0,0, result)
result

['180.000', '180.000', '180.000', '180.000', '200.000', '200.000']

In [75]:
# 机器人运动状态检测
def IsMotionDone():
    # 机器人运动状态检测
    result = []
    cps.HRIF_IsMotionDone(0, 0, result)
    if result[0]:
        print('机器人运动完成')
        return True
    else:
        print('机器人运动中...')
        return False

In [11]:
cps.HRIF_MoveL(boxID=0, rbtID=0, points=[350, 1, 350, -180, 5, -180], RawACSpoints=[0, 0, 90, 0, 90, 0], tcp="TCP", ucs="Base", speed=100, Acc=50, radius=50, isSeek=0, bit=0, state=0, cmdID="0")

0

In [54]:
# 停止运动
cps.HRIF_GrpStop(0,0)

0

In [58]:
cps.HRIF_MoveL(boxID=0, rbtID=0, points=[380, -300, 0, 180, 0, -160], RawACSpoints=[0, 0, 90, 0, 90, 0], tcp="TCP_1", ucs="Base", speed=3000, Acc=3000, radius=50, isSeek=0, bit=0, state=0, cmdID="0")

0

In [27]:
cps.HRIF_MoveJ(boxID=0, rbtID=0, points=[500, 0, 445, -180, 0, -180], RawACSpoints=[0, 0, 0, 0, 0, 0], tcp="TCP", ucs="Base", speed=180, Acc=50, radius=50, isJoint=0, isSeek=0, bit=0, state=0, cmdID="0")

0

In [57]:
cps.HRIF_MoveJ(boxID=0, rbtID=0, points=[500, 0, 445, -180, 0, -180], RawACSpoints=[0, 0, 90, 0, 90, 0], tcp="TCP", ucs="Base", speed=180, Acc=360, radius=50, isJoint=1, isSeek=0, bit=0, state=0, cmdID="0")

0

In [18]:
cps.HRIF_SetPayload(0, 0, 0.45, 0, 0, 120)

0

In [17]:
def GetCurrentPosition():
    """
    获取当前位置
    : return Pos: Type: dict
                    Key: "JointPos", "RealPos", "TcpPos", "UcsPos" 
                    Value: Type: list
                    Valus: 关节坐标：[J1, J2, J3, J4, J5, J6]
                            笛卡尔坐标：[X, Y, Z, RX, RY, RZ]
                            TCP坐标：[X, Y, Z, RX, RY, RZ]
                            用户坐标：[X, Y, Z, RX, RY, RZ]
    """
    result = []
    cps.HRIF_ReadActPos(0, 0, result)
    JointPos = [result[0], result[1], result[2], result[3], result[4], result[5]]
    RealPos = [result[6], result[7], result[8], result[9], result[10], result[11]]
    TcpPos = [result[12], result[13], result[14], result[15], result[16], result[17]]
    UcsPos = [result[18], result[19], result[20], result[21], result[22], result[23]]
    Pos = {"JointPos": JointPos, "RealPos": RealPos, "TcpPos": TcpPos, "UcsPos": UcsPos}
    return Pos

In [16]:
GetCurrentPosition()

{'JointPos': ['-37.717', '-9.464', '73.791', '-0.070', '96.835', '-57.725'],
 'RealPos': ['379.055',
  '-293.385',
  '489.163',
  '179.961',
  '-0.106',
  '-160.001'],
 'TcpPos': ['0.000', '0.000', '0.000', '0.000', '0.000', '0.000'],
 'UcsPos': ['0.000', '0.000', '0.000', '0.000', '0.000', '0.000']}

In [22]:
GetCurrentPosition()

{'JointPos': ['-1.211',
  '-21.224',
  '114.204',
  '180.000',
  '-44.572',
  '-201.210'],
 'RealPos': ['432.225', '-9.134', '0.030', '180.000', '-0.000', '-160.001'],
 'TcpPos': ['0.000', '0.000', '120.000', '0.000', '0.000', '0.000'],
 'UcsPos': ['0.000', '0.000', '0.000', '0.000', '0.000', '0.000']}

In [168]:
cps.HRIF_MoveRelJ(0, 0, 4, 1, 10)

20018

In [167]:
cps.HRIF_MoveRelJ(0, 0, 4, 0, 10)

0

In [156]:
cps.HRIF_MoveJ(boxID=0, rbtID=0, points=[0, 0, 0, 0, 0, 0], RawACSpoints=[0, 0, 90, 0, 90, 0], tcp="TCP", ucs="Base", speed=180, Acc=50, radius=50, isJoint=1, isSeek=0, bit=0, state=0, cmdID="0")

0

In [37]:
# 定义返回值空列表
result = [ ]
# 定义需要读取的位
nBit = 0
# 读取末端 nBit 位 DO 状态
nRet = cps.HRIF_ReadEndDO(0,0, nBit, result)
result

['0']

In [36]:
# 定义设置值
nVal = 0
# 定义需要设置的位
nBit = 0
# 设置末端 nBit 位 DO 状态
nRet = cps.HRIF_SetEndDO(0, 0, nBit, nVal)

In [152]:
# 停止运动
cps.HRIF_GrpStop(0,0)

0

In [154]:
# 暂停运动
cps.HRIF_GrpInterrupt(0,0)

0

In [155]:
# 继续运动
cps.HRIF_GrpContinue(0,0)

0

In [176]:
result = []
cps.HRIF_ReadRobotModel (0,0, result)
result[0]

'5KG'

# 2 Hans_Robot 函数

In [18]:
from Hans_Robot import HansRobot

In [19]:
Robot = HansRobot(Override=0.1, TcpName='TCP_1')
Robot.Connect()

http://192.168.4.40:20000
Connect to robot successfully! Robot load is 5KG.


In [15]:
Robot.GoHome()

Set robot speed to 10.0% Max Speed.
Move to [0, 0, 90, 0, 90, -20].
Home robot successfully!


In [28]:
Robot.OpenEndEffector()

In [10]:
Robot.MoveJ([0, 0, 90, 0, 90, -20], Override=0.1)

Set robot speed to 10.0% Max Speed.
Move to [0, 0, 90, 0, 90, -20].


In [21]:
Robot.MoveL([420, 0, 333, 180, 0, -160], Override=0.1)

Set robot speed to 10.0% Max Speed.
Move to [420, 0, 333, 180, 0, -160].


In [36]:
Robot.MoveL([591.5005692673324, -279.8694800153828, 41.1788488013284, -180.0, 0.0, -158.21649413185034], Override=0.1)

Set robot speed to 10.0% Max Speed.
Move to [591.5005692673324, -279.8694800153828, 41.1788488013284, -180.0, 0.0, -158.21649413185034].


In [20]:
Robot.Stop()

Stop robot successfully!


In [4]:
Robot.MoveRelJ(Axis=0, Direction=0, Distance=2)

Set robot speed to 10.0% Max Speed.
Move Axis 0 2° Negative.


In [8]:
# Robot.Reset()
Robot.Enable()

Enable robot successfully!


In [10]:
Robot.MoveL([400, 0, 300, 180, 0, -160], Override=0.1)

Set robot speed to 10.0% Max Speed.
Move to [400, 0, 300, 180, 0, -160].


In [17]:
Robot.MoveL([400, 0, 500, 180, 0, -160], Override=0.2)

Set robot speed to 20.0% Max Speed.
Move to [400, 0, 500, 180, 0, -160].


In [8]:
Robot.Reset()

Reset robot successfully!


In [12]:
Robot.Enable()

Enable robot successfully!


In [14]:
Robot.Interrupt()

Interrupt robot successfully!


In [7]:
Robot.Continue()

Continue robot successfully!


In [3]:
Robot.MoveL([350, -200, 0, -180, 5, -160], Override=0.2)

600.0 500.0
Move to [350, -200, 0, -180, 5, -160].


In [5]:
Robot.HP_Move([350, -200, 0, -180, 5, -160], Move_Type="L", Override=0.2)

Move to [350, -200, 0, -180, 5, -160].
The robot has reached the target position.


In [ ]:
Robot.Interrupt()

Interrupt robot successfully!


In [3]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = [1, 2, 3]
a + b

array([2, 4, 6])

In [6]:
workspace_limits_input = [[600, 200, 500], [200, -200, 100], [0, 0, 0]]
workspace_limits_input[0]
workspace_limits_input[1]
workspace_limits_input[2]

[600, 200, 500]

# 3 OpenCV & 相机

In [2]:
import cv2 as cv
import numpy as np

In [3]:
cap = cv.VideoCapture(0, cv.CAP_OBSENSOR)

if cap is None or not cap.isOpened():
    print("Warning: Unable to open the camera")
color = 0
depth = 0
depth8U = 0

In [ ]:
while True:
    if cap.grab() > 0:
        retval1, color = cap.retrieve(color, cv.CAP_OBSENSOR_BGR_IMAGE)
        cv.imshow("color", color)
    if cv.pollKey() > 0:
        break
cap.release()

# 4 Gemini2 函数

In [1]:
from hardware.Gemini_camera import OrbbecGeminiCamera

In [2]:
camera = OrbbecGeminiCamera()
camera.connect()

In [14]:
camera_param = camera.pipeline.get_camera_param()
camera.rgb_intrinsic = camera_param.rgb_intrinsic
camera.depth_intrinsic = camera_param.depth_intrinsic
camera.rgb_distortion = camera_param.rgb_distortion

In [3]:
camera.rgb_intrinsic

<OBCameraIntrinsic fx=512.412537 fy=512.491028 cx=322.733582 cy=234.740265 width=640 height=480>

In [4]:
camera.depth_intrinsic

<OBCameraIntrinsic fx=512.412537 fy=512.491028 cx=322.733582 cy=234.740265 width=640 height=480>

In [6]:
camera.get_image_bundle()

{'rgb': array([[[169, 171, 171],
         [169, 171, 171],
         [168, 170, 170],
         ...,
         [124, 129, 135],
         [120, 125, 131],
         [129, 134, 140]],
 
        [[169, 171, 171],
         [169, 171, 171],
         [168, 170, 170],
         ...,
         [ 87,  92,  98],
         [ 85,  90,  96],
         [ 89,  94, 100]],
 
        [[169, 171, 171],
         [168, 170, 170],
         [168, 170, 170],
         ...,
         [ 69,  66,  70],
         [ 70,  67,  71],
         [ 67,  64,  68]],
 
        ...,
 
        [[  5,   9,  11],
         [  3,   7,   9],
         [  2,   6,   8],
         ...,
         [119, 132, 163],
         [118, 131, 162],
         [117, 130, 161]],
 
        [[ 12,   8,   8],
         [ 10,   6,   6],
         [  7,   5,   5],
         ...,
         [119, 133, 162],
         [118, 132, 161],
         [117, 131, 160]],
 
        [[ 11,   7,   7],
         [  8,   4,   4],
         [  6,   4,   4],
         ...,
         [119, 133, 1

# 5 测试函数功能

In [22]:
import cv2 as cv
import numpy as np

In [17]:
# depth = cv.imread(r"E:\workspace\Anaconda\Robot\GRCNN\photo\filtered_depth_20240326_212200.tiff", cv.IMREAD_ANYDEPTH)
depth = cv.imread(r"E:\workspace\Anaconda\github\robotic-grasping\Jacquard\1a1ec1cfe633adcdebbf11b1629fc16a\0_1a1ec1cfe633adcdebbf11b1629fc16a_stereo_depth.tiff", cv.IMREAD_ANYDEPTH)
rgb = cv.imread(r"E:\workspace\Anaconda\github\robotic-grasping\Jacquard\1a1ec1cfe633adcdebbf11b1629fc16a\0_1a1ec1cfe633adcdebbf11b1629fc16a_RGB.png")

In [15]:
depth

array([[ 1.5762006,  1.5762006,  1.5762006, ...,  1.5751858,  1.5751858,
         1.5751858],
       [ 1.5762006,  1.5762006,  1.5762006, ...,  1.5751858,  1.5751858,
         1.5751858],
       [ 1.5762006,  1.5751858,  1.5751858, ...,  1.5751858,  1.5751858,
         1.5751858],
       ...,
       [-1.       ,  1.4297273,  1.4297273, ...,  1.4297273,  1.4297273,
         1.4297273],
       [-1.       ,  1.4297273,  1.4297273, ...,  1.4297273,  1.4297273,
         1.4297273],
       [-1.       ,  1.4297273,  1.4297273, ...,  1.4297273,  1.4297273,
         1.4297273]], dtype=float32)

In [18]:
rgb

array([[[177, 177, 177],
        [176, 176, 176],
        [177, 177, 177],
        ...,
        [190, 191, 191],
        [191, 191, 191],
        [192, 192, 192]],

       [[178, 178, 178],
        [178, 178, 178],
        [178, 178, 178],
        ...,
        [193, 193, 193],
        [193, 193, 193],
        [193, 193, 193]],

       [[178, 178, 178],
        [178, 178, 178],
        [178, 178, 178],
        ...,
        [194, 194, 194],
        [194, 194, 194],
        [194, 194, 194]],

       ...,

       [[171, 171, 171],
        [168, 167, 167],
        [167, 167, 167],
        ...,
        [183, 184, 184],
        [183, 185, 185],
        [184, 185, 185]],

       [[172, 172, 172],
        [170, 170, 170],
        [171, 171, 171],
        ...,
        [183, 184, 184],
        [183, 185, 185],
        [184, 185, 185]],

       [[169, 169, 169],
        [168, 169, 169],
        [169, 171, 171],
        ...,
        [183, 185, 185],
        [183, 185, 185],
        [184, 185, 185]]

In [19]:
def mouseclick_callback(event, x, y, flags, param):
    global depth_str, depth
    if event == cv.EVENT_LBUTTONDOWN: # 判断鼠标左键是否按下
        click_point_pix = (x, y)
        # 获取手动选择的像素点在相机坐标系下的坐标
        click_z = depth[click_point_pix[1]][click_point_pix[0]] # 获取深度图像中的深度值
        depth_str = f"Select Pixel Depth is {click_z[0]} mm" # 用于在图像上显示选择点深度值的字符串

In [20]:
def normalize_depth(frame): # 归一化深度图像
    # 使用全局最大值进行归一化
    global_max = 1500
    # 归一化深度图像
    normalized_frame = np.clip(frame / global_max * 255, 0, 255)
    return normalized_frame.astype(np.uint8)

In [24]:
depth_str = None
depth_image = normalize_depth(depth) # 使用时间滤波器对深度图像进行滤波
depth_image = cv.applyColorMap(depth_image, cv.COLORMAP_JET) # 将归一化后的深度图转换为伪彩色图像，以更好地观察深度变化
# 图像显示
cv.namedWindow('Depth') # 创建图像窗口
cv.setMouseCallback('Depth', mouseclick_callback) # 设置鼠标回调函数，RGB & Depth为窗口名，mouseclick_callback为回调函数
pixel_x, pixel_y = 10, 30 # 设置显示坐标的位置
cv.putText(depth_image, depth_str, (pixel_x, pixel_y), cv.FONT_HERSHEY_SIMPLEX, 0.5, (255, 255, 255), 1) # 0.5为字体大小，(0, 255, 0)为颜色，1为字体粗细
cv.imshow('RGB', rgb)
cv.imshow('Depth', depth_image)

: 

In [17]:
centroids_list = [(1, 8), (2, 8), (3, 8), (4, 8), (5, 8)]
for i in range(len(centroids_list)):
    click_point_pix = (int(centroids_list[i][0]), int(centroids_list[i][1]))
    print(click_point_pix)
    centroids_list = [(1+i, 8), (2+i, 8), (3+i, 8), (4+i, 8), (5+i, 8)]

(1, 8)
(2, 8)
(4, 8)
(6, 8)
(8, 8)
